name: Build and Dockerize

# triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# tasks
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # check repo
        uses: actions/checkout@v3

      - name: Set up QEMU # cross-platform constructions
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx # support for multi building
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers # cache for future / low weight
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image # building docker
        run: docker build -t helloworld_app:latest ./helloworld

      - name: List Docker images # test status of container
        run: docker images
