name: Build, Test Ansible, and Dockerize

on: # triggers
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: # what should be done
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository # check repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx # Multi-building support
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers # cache for future / low weight
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('helloworld/build.gradle', 'helloworld/settings.gradle') }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Python # configuration python env for ansible
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible and ansible-lint # install ansible and ansible-lint for checking ans-plb
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint

      - name: Run Ansible Lint # run testing prs for ansible plb
        run: ansible-lint ansible/playbook.yml

      - name: Build Docker image # build docker img
        run: docker build -t helloworld_app:latest ./helloworld

      - name: List Docker images # checking docker images
        run: docker images
